### ISSUE TITLE
CRI-O based Nodes Log Container Runtime Errors

### ISSUE THREAD

**Issue by icpenguins** [newrelic/nri-kubernetes#60]
The environment has a 4 node, bare-metal configuration. Two of the nodes are currently running Docker and two have been migrated to CRI-O due to Docker support being sunset starting in Kubernetes version 1.20 ([k8s blog](https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/)).

### Every 10 minutes
On the nodes running CRI-O as the container engine, the following log messages are printed every ten minutes.

```log
time="2020-12-18T00:18:18Z" level=error msg="debug error" component=Agent error="unable to determine open descriptor count for agent: open /host/proc/7/fd: no such file or directory"
...
time="2020-12-18T00:28:18Z" level=error msg="debug error" component=Agent error="unable to determine open descriptor count for agent: open /host/proc/7/fd: no such file or directory"
```

### Every 20 Seconds

```log
time="2020-12-18T00:28:18Z" level=warning msg="instantiating docker sampler process decorator" component="Metrics Process" error="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
time="2020-12-18T00:28:38Z" level=warning msg="instantiating docker sampler process decorator" component="Metrics Process" error="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
time="2020-12-18T00:28:58Z" level=warning msg="instantiating docker sampler process decorator" component="Metrics Process" error="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
```

## Expected Behavior

1. Log messages should provide actionable details for someone debugging to find out more information on how to address the issue.
2. The messages should not occur.

## Steps to Reproduce

Run CRI-O as your default container engine in a bare-metal environment.

## Your Environment

```shell
...@...:~$ k -n monitoring describe pod nri-bundle-newrelic-infrastructure-9jptt
Name:         nri-bundle-newrelic-infrastructure-9jptt
Namespace:    monitoring
Priority:     0
Node:         <redacted>
Start Time:   Thu, 17 Dec 2020 08:47:57 -0800
Labels:       app=newrelic-infrastructure
              controller-revision-hash=6d9d744546
              mode=privileged
              pod-template-generation=1
              release=nri-bundle
Annotations:  <none>
Status:       Running
IP:           <redacted>
IPs:
  IP:           <redacted>
Controlled By:  DaemonSet/nri-bundle-newrelic-infrastructure
Containers:
  newrelic-infrastructure:
    Container ID:   cri-o://91c8abb18a130b1431c952117f388084422094cd890215a4eca0de9f87d1c55f
    Image:          newrelic/infrastructure-k8s:1.26.6
    Image ID:       docker.io/newrelic/infrastructure-k8s@sha256:e88b843bf175408c9ab846f483763326cefd122247650043738255da812ce53a
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 17 Dec 2020 08:48:30 -0800
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  300M
    Requests:
      cpu:     100m
      memory:  150M
    Environment:
      NRIA_LICENSE_KEY:              <set to the key 'license' in secret 'nri-bundle-newrelic-infrastructure-config'>  Optional: false
      CLUSTER_NAME:                  <redacted>
      NRK8S_NODE_NAME:                (v1:spec.nodeName)
      NRIA_DISPLAY_NAME:              (v1:spec.nodeName)
      NRIA_CUSTOM_ATTRIBUTES:        {"clusterName":"$(CLUSTER_NAME)"}
      NRIA_PASSTHROUGH_ENVIRONMENT:  KUBERNETES_SERVICE_HOST,KUBERNETES_SERVICE_PORT,CLUSTER_NAME,CADVISOR_PORT,NRK8S_NODE_NAME,KUBE_STATE_METRICS_URL,KUBE_STATE_METRICS_POD_LABEL,TIMEOUT,ETCD_TLS_SECRET_NAME,ETCD_TLS_SECRET_NAMESPACE,API_SERVER_SECURE_PORT,KUBE_STATE_METRICS_SCHEME,KUBE_STATE_METRICS_PORT,SCHEDULER_ENDPOINT_URL,ETCD_ENDPOINT_URL,CONTROLLER_MANAGER_ENDPOINT_URL,API_SERVER_ENDPOINT_URL,DISABLE_KUBE_STATE_METRICS,DISCOVERY_CACHE_TTL
    Mounts:
      /dev from dev (rw)
      /host from host-volume (ro)
      /var/log from log (rw)
      /var/run/docker.sock from host-docker-socket (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from nri-bundle-newrelic-infrastructure-token-cgg6w (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:
  host-docker-socket:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/docker.sock
    HostPathType:
  log:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log
    HostPathType:
  host-volume:
    Type:          HostPath (bare host directory volume)
    Path:          /
    HostPathType:
  nri-bundle-newrelic-infrastructure-token-cgg6w:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  nri-bundle-newrelic-infrastructure-token-cgg6w
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     :NoSchedule op=Exists
                 :NoExecute op=Exists
                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists
                 node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                 node.kubernetes.io/unreachable:NoExecute op=Exists
                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:          <none>

...@...:~$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:57:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

...@...:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```

**Comment by tmcowner** [comment]
same problem here

**Comment by roobre** [comment]
Hi, thanks for taking the time to report this and the detailed information!

Are you able to reproduce this behavior with the latest version of the `newrelic/infrastructure-k8s` image?

Our kubernetes solution does not depend on Docker, so these log messages are benign. The infrastructure agent, which is used to collect some metrics from the node, might be trying to mistakenly probe Docker for a docker installation and therefore cause these messages. I have forwarded this to the agent team so they can take a quick look.

Please come back to us if this is still happening with the latest image, as there have been quite a few changes and bugfixes since this was opened.

**Comment by jaygridley** [comment]
Same issue with with privileged mode and AKS 1.19

**Comment by roobre** [comment]
Hey there,

Thanks for bringing this to our attention. This message actually does not come from the nri-kubernetes integration, but rather from the infrastructure agent. In this case is a benign message and does not reflect a real problem.

We are aware that despite this, it creates noise and doesn't really provide any actionable point. We are stashing a nice amount of goodies for the upcoming version 3 of the integration, and we are planning to get rid of this message in that release as well. Please stay tuned!

**Comment by vposhamod** [comment]
Same issue here with AKS 1.20.9. Our logging with NR isn't working and this error is causing noise.

**Comment by roobre** [comment]
This has been fixed in v3 version of the integration, actually a couple months ago. For some reason this issue slipped under our radar.

More details on v3 can be found in our docs here: https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/get-started/changes-since-v3

**Comment by pie-r** [comment]
Hello @roobre I still see the same issue:
```
newrelic-bundle-nrk8s-kubelet-drnv2 agent time="2022-05-14T18:40:27Z" level=error msg="debug error" component=Agent error="unable to determine open descriptor count for agent: open /host/proc/7/fd: no such file or directory"
newrelic-bundle-nrk8s-kubelet-drnv2 agent time="2022-05-14T18:50:27Z" level=error msg="debug error" component=Agent error="unable to determine open descriptor count for agent: open /host/proc/7/fd: no such file or directory"
newrelic-bundle-nrk8s-kubelet-drnv2 agent time="2022-05-14T19:00:27Z" level=error msg="debug error" component=Agent error="unable to determine open descriptor count for agent: open /host/proc/7/fd: no such file or directory"
newrelic-bundle-nrk8s-kubelet-drnv2 agent time="2022-05-14T19:10:27Z" level=error msg="debug error" component=Agent error="unable to determine open descriptor count for agent: open /host/proc/7/fd: no such file or directory"
newrelic-bundle-nrk8s-kubelet-drnv2 agent time="2022-05-14T19:20:27Z" level=error msg="debug error" component=Agent error="unable to determine open descriptor count for agent: open /host/proc/7/fd: no such file or directory"
newrelic-bundle-nrk8s-kubelet-drnv2 agent time="2022-05-14T19:30:27Z" level=error msg="debug error" component=Agent error="unable to determine open descriptor count for agent: open /host/proc/7/fd: no such file or directory"
```

Bundle version: 4.4.5

**Comment by roobre** [comment]
Hey @pie-r ,
I believe this is actually a different error. However, it is true that it should not be showing in there if you're running this in unprivileged (`privileged: false`) mode. I'll get in touch with the agent team to inform them about this.

**Comment by pie-r** [comment]
Thank you, looking forward for the patch, please update this issue or link the new one so I can follow ;)

**Comment by roobre** [comment]
@pie-r  PR is in the works here: https://github.com/newrelic/nri-kubernetes/pull/467
